### ISSUE TITLE
Is this still in Development? Use case for Volve Daataset

### ISSUE THREAD

**Issue by discover-volve** [mwentzWW/PetroAlchemy#5]
I would like to create a demo file for the Volve dataset and use this as a standard tool for developing the analysis around the dataset for my website: www.DiscoverVolve.com 

Please let me know if this project is still under development.

**Comment by mwentzWW** [comment]
This project is still being developed! I am currently the only contributor, but I am working on a major update right now that will hopefully make it out soon. I totally agree with your project's vision! I created PetroAlchemy for similar reasons of helping people learn using something intuitive.

**Comment by discover-volve** [comment]
Thank you! All the best with the new update.
